### ISSUE TITLE
RestClient::Unauthorized: 401 Unauthorized

### ISSUE THREAD

**Issue by iamrishirawat** [nikkypx/omdb-api#1]
Hi,

I'm using the gem as mentioned in the documentation but getting this error:

RestClient::Unauthorized: 401 Unauthorized

**Comment by nikkypx** [comment]
Hi,

Thanks for opening this. Yes, it appears the API now requires a key. I will make an update.

**Comment by nikkypx** [comment]
New version pushed, let me know if you have any problems.
