### ISSUE TITLE
Version 1.1.0 - unable to access movie attributes

### ISSUE THREAD

**Issue by benpolinsky** [nikkypx/omdb-api#2]
Hi,

I tried using the latest version of this library, but wasn't able to access any attributes on a Movie result. 

Using the search api, I receive a collection of movies which I can iterate through. However, it seems like all of the params set with klass_param are cased incorrectly and are inaccessible (my first guess). I think I know where the issue is, so I'll try to get a PR in today for you. 

Downgrading to 1.0.0 solves the issue.

Let me know if you can replicate.

Thanks (and thanks for the library)

**Comment by nikkypx** [comment]
Thanks for submitting issue, I've pushed up 1.2, this should be fixed. Let me know if you have any other issues.
