### ISSUE TITLE
Cannot access result attributes

### ISSUE THREAD

**Issue by gouvermxt** [nikkypx/omdb-api#3]
When I try to access any Movie or Error attribute I get an error like:

`undefined method `imdb_id' for #<Omdb::Api::Movie:0x00007fbd4673be18>`

The workaround is to use `instance_variable_get`.

Ruby: 2.6.0
Rails: 5.2.3

**Comment by nikkypx** [comment]
I'll take a look

**Comment by nikkypx** [comment]
Should be fixed, bump to the latest version, let me know if you have any issues
